FROM node:24-alpine

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    sqlite-dev \
    py3-setuptools

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 5173

ENV TZ=Asia/Tokyo

CMD ["sh", "-c", "npm run dev"]