services:
  backend_dev:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    image: be_transcendence_backend_dev
    container_name: be_transcendence_backend_dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: tail -f /dev/null
volumes:
  node_modules:
