openapi: 3.0.3
info:
  title: Fastify demo API
  description: The official Fastify demo API
  version: 0.1.0
components:
  schemas: {}
paths:
  /api/common/auth/users:
    get:
      tags:
        - Auth
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    password:
                      type: string
                    salt:
                      type: string
                  required:
                    - id
                    - name
                    - password
                    - salt
  /api/common/auth/login:
    post:
      tags:
        - Auth
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /api/common/auth/me:
    post:
      tags:
        - Auth
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
